# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.2.0.0
group=com.coolerpromc.fishtrap
java_version=25

# Common
minecraft_version=26.2
mod_name=FishTrap
mod_author=CoolerProMC
mod_id=fishtrap
license=MIT
credits=
description=Fish trap can let you get fish without fishing
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.160.0+26.2
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.88
neoforge_loader_version_range=[4,)

# Optional integrations (compile only), see https://maven.blamejared.com/mezz/jei and https://modrinth.com/mod/jade
jei_version=30.32.0.221
jade_version=26.2.10

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
